
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "simpledotcss/simple.min.css";
import { connection } from 'next/server';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connection(); // 요청이 실제로 들어올 때까지 기다린 뒤 그 시점에 렌더링

  return (
    <html lang="en">
      <body>
        <Header></Header>
          {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
